<h2>Fanbot 1.0</h2>
<p>I had a problem. The problem was that it was too hot at night, but too cold in the morning in my rented condo. I built a contraption to turn the fan on and off using a Lego NXT and linear actuator.</p>
<video width="640" height="480" controls>
    <source src="/static/vid/fanbot1.mp4" type="video/mp4">
</video>
<h2>Fanbot 2.0</h2>
<p>Mechanical parts for version 2.0 were printed by Shapeways. An arduino with a pololu motor controller and an RTC module from sparkfun were attached precariously with zip ties.</p>
<img src="static/fanbot2.jpg">
<video width="640" height="480" controls>
    <source src="/static/vid/fanbot2.mp4" type="video/mp4">
</video>
<h2>Fanbot 3.0</h2>
<p>I now live in my own house with my very own programmable thermostat.</p>
