<form method="POST">
	<h1>Login</h1>
	<?php if (isset($error)) { ?>
	<p><?=$error?></p>
	<?php } else { ?>
	<p>Let's go ahead and get you logged in.</p>
	<?php } ?>
	<label>Username</label>
	<input type="text" name="username">
	<br/>
	<label>Password</label>
	<input type="password" name="password">
	<br/>
	<label>Stay Logged In</label>
	<input type="checkbox" name="cookie">
	<br/>
	<label>&nbsp;</label>
	<input type="submit" value="Login">
</form>
