<h2>web-TipiT</h2>
<p>
	TipiT is a palindrome. It's also a tip calculator that produces bills with interesting digit sequences. There's also a <a href="http://github.com/rparrett/tipit">native android version</a>.
</p>
<div class="tipControls">
	<h2>Controls</h2>
	<p></p>
	<div>
		<label for="min">Range</label>
		<div id="rangeSlider"></div>
		<span id="min">15%</span> - 
		<span id="max">20%</span>
	</div>
	<div>
		<label>Bill Total</label>
		<input type="number" step="0.01" id="billTotal">
	</div>
	<div>
		<label>Tip On</label>
		<input type="number" step="0.01" id="tipOn"><br/>
	</div>
</div>
<div>
	<h2>Results</h2>
	<p>
		<span id="noResults">None, so far.</span>
	</p>
	<div id="results">
	</div>
</div>
